import { Interface } from 'reliant-type';

export const AllFormatTypesSchema = Interface({
  name: "string",
  age: "number",
  active: "boolean",
  created: "date",
  data: "any",
  obj: "object",
  unknown: "unknown",
  email: "email",
  website: "url",
  id: "uuid",
  mobile: "phone",
  server: "ip",
  config: "json",
  color: "hexcolor",
  encoded: "base64",
  token: "jwt",
  version: "semver",
  urlSlug: "slug",
  description: "text",
  userPassword: "password",
  username: "username",
  count: "int",
  positiveNum: "positive",
  negativeNum: "negative",
  floatNum: "float",
  doubleNum: "double",
  integerNum: "integer",
  metadata: "record<string,any>",
  headers: "record<string,string>",
  counts: "record<string,number>",
});